apiVersion: v1
kind: Service
metadata:
  name: master
  namespace: archive
spec:
  selector:
    app: master
  ports:
  - port: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: archive
spec:
  selector:
    app: worker
  ports:
  - port: 5432